### PR TITLE
don't dereference members that are null

### PR DESCRIPTION
**Pull request by seeekr**

### CODE REVIEW

**Comment by seeekr** [comment]
I don't have a specific test case to show that `path.node` or `path.node.right` can be null, but that has been happening in our parsing of valid JS code, and we're using this patch in production, so wanted to contribute it back.
I couldn't think of a better commit message because I don't understand well enough what exactly is going on, what exactly the given properties being null means from a logical perspective -- so feel free to adjust the commit message, of course :)

Cheers!

**Comment by erikdesjardins** [comment]
Thanks!

I changed the check to `t.isAssignmentExpression` which should be at least as strict (if not more), but let me know if it doesn't work.

Will be released momentarily.

**Comment by erikdesjardins** [comment]
Released in 2.2.2 https://github.com/erikdesjardins/babel-plugin-transform-dead-code-elimination/releases/tag/v2.2.2

**Comment by seeekr** [comment]
Awesome, thanks! Will report with feedback!

**Comment by seeekr** [comment]
Changes are looking good, client says things are working well! Thanks again!

**Pull request merged**
